[OPS-2105] Improve error reporting output
juiceinc/devlandia pull request #102
Opened 2021-04-14 20:29 UTC by obscure-shadow

Ticket: [OPS-2105](https://juiceanalytics.atlassian.net/browse/OPS-2105)
Type: Improvement

#### This PR introduces the following changes

- updated check_call to remove traceback and only print specific error

Previously looked like this: 

```
Traceback (most recent call last):
  File "/Users/david.paul/.virtualenvs/devlandia/bin/jb", line 33, in <module>
    sys.exit(load_entry_point('jbcli', 'console_scripts', 'jb')())
  File "/Users/david.paul/.virtualenvs/devlandia/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/david.paul/.virtualenvs/devlandia/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/david.paul/.virtualenvs/devlandia/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/david.paul/.virtualenvs/devlandia/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/david.paul/.virtualenvs/devlandia/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/david.paul/.virtualenvs/devlandia/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/david.paul/Desktop/devlandia/jbcli/jbcli/cli/jb.py", line 466, in start
    dockerutil.up(env=environ, ganesha=ganesha)
  File "/Users/david.paul/Desktop/devlandia/jbcli/jbcli/utils/dockerutil.py", line 93, in up
    docker_compose(['up', '--abort-on-container-exit'], env=env, ganesha=ganesha)
  File "/Users/david.paul/Desktop/devlandia/jbcli/jbcli/utils/dockerutil.py", line 87, in docker_compose
    return check_call(cmd + file_args + args, env=env)
  File "/Users/david.paul/Desktop/devlandia/jbcli/jbcli/utils/subprocess.py", line 25, in check_call
    return subprocess.check_call(args, env=env)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker-compose', '--project-directory', '.', '--project-name', 'core', '-f', '../docker-compose.common.yml', '-f', 'docker-compose.yml', 'up', '--abort-on-container-exit']' returned non-zero exit status 1.
```
now it just does: 

```
Error:
      Command '['docker-compose', '--project-directory', '.', '--project-name', 'core', '-f', '../docker-compose.common.yml', '-f', 'docker-compose.yml', 'up', '--abort-on-container-exit']' returned non-zero exit status 1.
```

I attempted to do the same with `check_output` but couldn't figure out a way that it did not cause errors that were not there previously. I am open to new ideas though

2021-04-14 20:33 UTC, cwire4 commented
It might be good to add something like a verbose flag or something and if set shows the full traceback, but by default just show the shortened error.

2021-04-14 20:39 UTC, obscure-shadow commented
> It might be good to add something like a verbose flag or something and if set shows the full traceback, but by default just show the shortened error.

The theory behind this idea was that the tracebacks are very generally not useful and the actual error is further up in the output, in this case 

```
postgres_1  | 2021-04-14 20:26:08.282 UTC [1] FATAL:  could not write lock file "postmaster.pid": No space left on device
redis_1     | 1:M 14 Apr 20:26:08.128 * DB loaded from disk: 0.000 seconds
redis_1     | 1:M 14 Apr 20:26:08.128 * Ready to accept connections
core_postgres_1 exited with code 1
```

is output further up, and the traceback doesn't really give any real info besides that the subprocess  encountered an error

2021-04-14 20:48 UTC, cwire4 commented
In general, that's true, but there have definitely been cases where the relevant error is only in the traceback like if Docker isn't running and you try to run jb start it (you get a requests ConnectionError I believe).  So it would be nice to be able to see it if needed.

2021-04-15 15:11 UTC, radix requested changes

2021-04-15 15:11 UTC, radix commented on jbcli/jbcli/utils/subprocess.py
> +        echo_warning(f"Error:\n      {e}\n")
can you include the command in this error message?

2021-04-15 15:12 UTC, radix commented on jbcli/jbcli/utils/subprocess.py
> +        echo_warning(f"Error:\n      {e}\n")
NEVER MIND I see now that the error stringifies with the command :)

2021-04-15 15:12 UTC, radix commented
@cwire4 this only swallows the subprocess CalledProcessErrors, not the docker ConnectionErrors

2021-04-15 15:17 UTC, cwire4 commented
Cool

2021-04-15 18:12 UTC, obscure-shadow commented
so @radix @cwire4 should I not worry about verbose mode?

2021-04-15 18:14 UTC, cwire4 commented
I guess for now, if we run into an issue where it helps we can add it then.

2021-04-15 18:22 UTC, cwire4 approved these changes

2021-04-15 18:41 UTC, radix approved these changes

2021-04-15 18:43 UTC, merged