[OPS-2099] Remove unused Commands from Jb-cli
juiceinc/devlandia pull request #91
Opened 2021-02-25 22:34 UTC by obscure-shadow

Ticket: [OPS-2099](https://juiceanalytics.atlassian.net/browse/OPS-2099)
Type: Improvement

#### This PR introduces the following changes

- Removed commands test_app, upload, create, package, and search

2021-02-26 14:52 UTC, chrisgemignani requested changes
Good start. There will be test code associated with these commands in jbcli/tests to delete also. LMK if you want help getting the tests running.

2021-02-26 22:39 UTC, obscure-shadow commented
@chrisgemignani made some changes, also updated requirements in this pr.

2021-03-04 17:48 UTC, chrisgemignani commented
LGTM; tested locally and things were :+1:

Two things for followup work
* The --runtime parameter can be removed. 
* Py2 compatibility can be removed (like from `__future__ import print_function` and `from six import`)

2021-03-04 17:49 UTC, chrisgemignani approved these changes

2021-03-04 17:58 UTC, merged